"""
pipeline/download_test_images.py — A.R.I.A. Test Image Downloader
Downloads sample road_damage images for pipeline testing.
Falls back to a generated dummy image if download fails.
"""

import os
import sys

import cv2
import numpy as np
import requests

# ─────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────
OUTPUT_DIR = "pipeline/test_images"

TEST_IMAGE_URLS = [
    (
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/"
        "Pothole_on_a_road_in_India.jpg/640px-Pothole_on_a_road_in_India.jpg",
        "road_damage_india_01.jpg",
    ),
    (
        "https://upload.wikimedia.org/wikipedia/commons/3/3e/Bad_Road.jpg",
        "road_damage_india_02.jpg",
    ),
]


def _create_dummy_image(save_path: str, index: int) -> None:
    """
    Create a synthetic road_damage dummy image using OpenCV.

    Generates a gray road surface with a darker cracked region
    to simulate a defect detection target when real images cannot
    be downloaded.

    Args:
        save_path (str): Full path where the dummy image will be saved.
        index (int): Image number (used to vary appearance slightly).
    """
    h, w = 480, 640
    # Gray road surface
    img = np.full((h, w, 3), fill_value=130 + index * 5, dtype=np.uint8)

    # Add a fake road_damage crack region
    cx, cy = w // 2 + index * 40, h // 2 + index * 20
    cv2.ellipse(img, (cx, cy), (60 + index * 10, 30),
                0, 0, 360, (60, 55, 50), -1)
    cv2.ellipse(img, (cx, cy), (62 + index * 10, 32),
                0, 0, 360, (40, 35, 30), 2)

    # Lane markings
    for x in range(0, w, 80):
        cv2.rectangle(img, (x, h - 30), (x + 40, h - 10), (220, 220, 180), -1)

    # Label text
    cv2.putText(
        img,
        f"[ARIA DUMMY road_damage #{index + 1}]",
        (10, 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.6,
        (200, 200, 200),
        1,
    )

    cv2.imwrite(save_path, img)
    print(f"   🖼  Created dummy image: {save_path}")


def download_test_images(output_dir: str = OUTPUT_DIR) -> list[str]:
    """
    Download road_damage sample images for inference testing.

    Attempts to download each image from the configured URLs using
    requests. If a download fails (network errors, HTTP errors, etc.),
    a synthetic dummy image is generated by OpenCV as a fallback.

    Args:
        output_dir (str): Directory to save the downloaded/generated images.

    Returns:
        list[str]: Absolute paths to all saved images.
    """
    os.makedirs(output_dir, exist_ok=True)
    saved_paths: list[str] = []

    for i, (url, filename) in enumerate(TEST_IMAGE_URLS):
        save_path = os.path.join(output_dir, filename)

        if os.path.exists(save_path):
            print(f"✅ Already exists: {save_path}")
            saved_paths.append(os.path.abspath(save_path))
            continue

        print(f"📥 Downloading {filename} …")
        try:
            resp = requests.get(url, timeout=15, stream=True)
            resp.raise_for_status()

            with open(save_path, "wb") as f:
                for chunk in resp.iter_content(chunk_size=8192):
                    f.write(chunk)

            size_kb = os.path.getsize(save_path) / 1024
            print(f"✅ Saved: {save_path}  ({size_kb:.1f} KB)")
            saved_paths.append(os.path.abspath(save_path))

        except Exception as exc:
            print(f"⚠️  Download failed for '{filename}': {exc}")
            print(f"   Generating synthetic fallback image instead …")
            _create_dummy_image(save_path, index=i)
            saved_paths.append(os.path.abspath(save_path))

    print(f"\n✅ {len(saved_paths)} test image(s) ready in '{output_dir}'.")
    return saved_paths


if __name__ == "__main__":
    paths = download_test_images()
    for p in paths:
        print(f"  • {p}")
